## Матричный метод

Матричный метод может применяться в решении систем линейных уравнений, в которых число неизвестных равно числу уравнений, то есть систем линейных уравнений с квадратной матрицей коэффициентов при неизвестных.
Решение системы линейных алгебраических уравнений по матричному методу определяется равенством:
$$ X = A^{-1} * B $$


Где
$$
{A} = 
\left\lgroup\begin{matrix}
a_{11} & a_{12} & ... & a_{1n} \cr
a_{21} & a_{22} & ... & a_{2n} \cr
a_{n1} & a_{n2} & ... & a_{nn}
\end{matrix}\right\rgroup - матрица системы
$$
$$
{X} = 
\left\lgroup\begin{matrix}
x_{1} \cr
x_{2} \cr
... \cr
x_{n}
\end{matrix}\right\rgroup - столбец неизвестных
$$
$$
{B} = 
\left\lgroup\begin{matrix}
b_{1} \cr
b_{2} \cr
... \cr
b_{n}
\end{matrix}\right\rgroup - столбец свободных коэффициентов
$$

В  случае, если определитель A не равен нулю, то у системы имеется только один вариант решения: при помощи метода обратной матрицы. Если определитель A = 0, то систему нельзя решить данным методом.

In [39]:
import numpy as np

A = np.random.randint(-10,10,(3,3))
B = np.random.randint(-10,10,(3,1))

print("Матрица A:\n", A)
print("\nСтолбец свободных коэффициентов B:\n", B)

Матрица A:
 [[ 9  9 -5]
 [-2 -9  2]
 [ 5  4 -1]]

Столбец свободных коэффициентов B:
 [[-7]
 [ 1]
 [ 3]]


In [40]:
A_det = np.linalg.det(A)  # Определитель A

if A_det != 0:
    # Находим обратную и присоединенную матрицу
    A_inv = np.linalg.inv(A)
    R = A_inv.dot(B)
    print("X =\n", R)
    
else:
    print("Определитель равен 0, систему решить нельзя")

X =
 [[0.95192308]
 [0.61538462]
 [4.22115385]]


## Метод Крамера

Метод Крамера предназначен для того, чтобы решать системы линейных алгебраических уравнений (СЛАУ), в которых число неизвестных переменных равняется числу уравнений, а определитель основной матрицы не равен нулю, то есть матрица невырожденная.

Формулы для нахождения неизвестных переменных по методу Крамера:

$
x_1 = \frac{\triangle_1}{\triangle},
$

$
x_2 = \frac{\triangle_2}{\triangle},
$

$
x_{3} = \frac{\triangle_3}{\triangle}.
$

In [41]:
import numpy as np

A = np.random.randint(-10,10,(3,3))
B = np.random.randint(-10,10,(3,1))

print("Матрица A:\n", A)
print("\nСтолбец свободных коэффициентов B:\n", B)

Матрица A:
 [[ 3 -4  3]
 [-3  7  7]
 [-4 -9  7]]

Столбец свободных коэффициентов B:
 [[-7]
 [-8]
 [-9]]


In [43]:
A_det  = np.linalg.det(A)  # Определитель A

if A_det != 0:
    # Найдем неизветсные переменные по методу Крамера
    det_1 = A.copy() 
    det_1 [:, 0] = B[:, 0] 
    x1 = np.linalg.det(det_1) / A_det
    
    det_2 = A.copy()  
    det_2[:, 1] = B[:, 0] 
    x2 = np.linalg.det(det_2) / A_det
    
    det_3 = A.copy() 
    det_3[:, 2] = B[:, 0] 
    x3 = np.linalg.det(det_3) / A_det
   
    print("x1 = ", round(x1,3), "\nx2 = ", round(x2,3), "\nx3 = ", round(x3,3))
else:
    print("Определитель равен 0, то есть матрица вырожденная и нельяз решить данным методом")

x1 =  -0.664 
x2 =  0.104 
x3 =  -1.531
